# Generated by Django 4.1.1 on 2022-10-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('parentezco', models.CharField(max_length=30)),
                ('anio_nacimiento', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('fecha_registro', models.DateTimeField()),
                
            ],
        ),
    ]
